apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}
data:
  DB_HOST: {{.Values.postgresql.auth.host}}
  DB_NAME: {{.Values.postgresql.auth.username}}
  DB_USER: {{.Values.postgresql.auth.postgrepasss}}
