apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}
stringData:
    APP_KEY: {{ .Values.stringData}}
    DB_ROOT_PWSD: {{ .Values.stringData}}
    DB_PSWD: {{ .Values.stringData}}
